#!/usr/bin/env node
// gen_risk_register.mjs — generate docs/admin/RISK_REGISTER.md จาก CIA_MISSION + handoffs
// รัน: node scripts/admin/gen_risk_register.mjs
// Output: docs/admin/RISK_REGISTER.md (overwritten)

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = process.cwd();
const OUTPUT = join(ROOT, 'docs/admin/RISK_REGISTER.md');
const CIA_FILE = join(ROOT, 'docs/CIA_MISSION.md');
const HANDOFF_DIR = join(ROOT, 'handoffs');

if (!existsSync(CIA_FILE)) {
  console.error('docs/CIA_MISSION.md ไม่พบ');
  process.exit(1);
}

if (!existsSync(join(ROOT, 'docs/admin'))) mkdirSync(join(ROOT, 'docs/admin'), { recursive: true });

const cia = readFileSync(CIA_FILE, 'utf8');

// extract risk register table จาก CIA_MISSION
const riskTableMatch = cia.match(/\| ID \| Risk \|[\s\S]*?(?=\n\n|\n###|$)/);
const riskLines = riskTableMatch
  ? riskTableMatch[0].split('\n').filter(l => l.trim().startsWith('| R-'))
  : [];

// ดึง risks จาก handoffs ล่าสุดของ CIA
const ciaHandoffs = existsSync(HANDOFF_DIR)
  ? readdirSync(HANDOFF_DIR).filter(f => f.startsWith('CIA_') && f.endsWith('.md')).sort().reverse()
  : [];
const latestCIA = ciaHandoffs[0];
let extendedRisks = [];
if (latestCIA) {
  const handoff = readFileSync(join(HANDOFF_DIR, latestCIA), 'utf8');
  const tableMatch = handoff.match(/\| ID \| Risk \|[\s\S]*?(?=\n\n|\n##|$)/);
  if (tableMatch) {
    extendedRisks = tableMatch[0].split('\n').filter(l => l.trim().startsWith('| R-'));
  }
}

// merge — handoff overrides CIA (handoff = live state)
const riskMap = new Map();
for (const line of [...riskLines, ...extendedRisks]) {
  const idMatch = line.match(/^\| (R-\d+)/);
  if (idMatch) riskMap.set(idMatch[1], line);
}

const sortedRisks = [...riskMap.entries()]
  .sort(([a], [b]) => parseInt(a.slice(2)) - parseInt(b.slice(2)));

// ดึง T-NN transferred items
const transferMap = new Map();
if (latestCIA) {
  const handoff = readFileSync(join(HANDOFF_DIR, latestCIA), 'utf8');
  const transferMatches = [...handoff.matchAll(/### (T-\d+)[^\n]*?— ([^\n(]+)/g)];
  for (const [, id, title] of transferMatches) {
    transferMap.set(id, title.trim());
  }
}

// ─── Build markdown ────────────────────
const now = new Date().toISOString().split('T')[0];

const out = `# CIA Risk Register — live
# Generated by scripts/admin/gen_risk_register.mjs at ${now}
# ห้ามแก้ไฟล์นี้โดยตรง — แก้ที่ docs/CIA_MISSION.md หรือ handoffs/CIA_*.md แล้ว regenerate

> **Source of truth:**
> - Charter risks (R-01..R-14): \`docs/CIA_MISSION.md\` § 3.2
> - Extended risks + status: \`handoffs/${latestCIA || 'CIA_*.md'}\`

## Risk register (${sortedRisks.length} risks)

| ID | Risk | Priority/Status | Source |
|---|---|---|---|
${sortedRisks.map(([, line]) => line.trim()).join('\n') || '_(empty)_'}

## Transferred items (T-NN → R-NN cross-link)

${transferMap.size === 0 ? '_(no T-NN transfers found)_' :
  [...transferMap.entries()]
    .sort(([a], [b]) => parseInt(a.slice(2)) - parseInt(b.slice(2)))
    .map(([id, title]) => `- **${id}** — ${title}`)
    .join('\n')}

## ลำดับการอ่าน

1. **อ่านไฟล์นี้** — overview risks + status
2. \`docs/CIA_MISSION.md\` — full context (threat model, decision framework, SOPs)
3. \`handoffs/${latestCIA || 'CIA_*.md'}\` — live task state, blocked/pending/done

## คำสั่ง maintenance

\`\`\`bash
# regenerate ไฟล์นี้
node scripts/admin/gen_risk_register.mjs

# ตรวจ handoff format
node scripts/admin/handoff_lint.mjs handoffs/${latestCIA || 'CIA_*.md'}

# BIG overview
node scripts/admin/big_status.mjs --verbose
\`\`\`
`;

writeFileSync(OUTPUT, out);
console.log(`✓ wrote ${OUTPUT}`);
console.log(`  ${sortedRisks.length} risks, ${transferMap.size} transferred items`);
