#!/usr/bin/env node
// แปลง CSV จาก julian_keygen.html → SQL สำหรับ import เข้า CF D1
//
// วิธีใช้:
//   node julian_import.mjs julian_mk_1700-2100.csv > import_master.sql
//   wrangler d1 execute julian --file=import_master.sql
//
// หรือ import Internet Table:
//   node julian_import.mjs julian_internet_2026-05-21.jsonl > import_internet.sql
//   wrangler d1 execute julian --file=import_internet.sql

import { readFileSync } from 'fs';
import { basename } from 'path';

const BATCH = 500; // rows per INSERT statement

const file = process.argv[2];
if (!file) {
  console.error('Usage: node julian_import.mjs <file.csv|file.jsonl>');
  process.exit(1);
}

const content = readFileSync(file, 'utf8').trim();
const isJSONL = file.endsWith('.jsonl');

if (isJSONL) importInternet(content);
else importMasterKey(content);

// ── Master Key (CSV) ──────────────────────────────────────────

function importMasterKey(csv) {
  const lines = csv.split('\n');
  const header = lines[0].split(','); // jd,date_ce,su,mo,ma,me,ju,ve,sa,ra,ke,mr
  const cols = header.slice(2); // su..mr (skip jd, date_ce)

  console.log('-- Master Key import');
  console.log('-- Generated by julian_import.mjs');
  console.log(`-- Source: ${basename(file)}`);
  console.log(`-- Rows: ${lines.length - 1}\n`);

  const rows = lines.slice(1).filter(Boolean);
  for (let i = 0; i < rows.length; i += BATCH) {
    const batch = rows.slice(i, i + BATCH);
    const values = batch.map(line => {
      const parts = line.split(',');
      const jd = parts[0];
      const planets = parts.slice(2).map(v => parseFloat(v).toFixed(4));
      return `(${jd},${planets.join(',')})`;
    }).join(',\n  ');
    console.log(`INSERT OR IGNORE INTO master_key (jd,su,mo,ma,me,ju,ve,sa,ra,ke,mr) VALUES\n  ${values};\n`);
  }
}

// ── Internet Table (JSONL) ────────────────────────────────────

function importInternet(jsonl) {
  const records = jsonl.split('\n').filter(Boolean).map(line => JSON.parse(line));

  console.log('-- Internet Table import');
  console.log('-- Generated by julian_import.mjs');
  console.log(`-- Source: ${basename(file)}`);
  console.log(`-- Rows: ${records.length}\n`);

  for (let i = 0; i < records.length; i += BATCH) {
    const batch = records.slice(i, i + BATCH);
    const values = batch.map(r => {
      const relate = r.relate_id?.length ? JSON.stringify(r.relate_id) : null;
      return `(${[
        r.jd,
        sql(r.name),
        sql(r.event_label),
        sql(r.type),
        sql(r.country ?? null),
        r.tier ?? 'NULL',
        r.lat ?? 'NULL',
        r.lng ?? 'NULL',
        sql(r.time_utc),
        r.lagna_sign ?? 'NULL',
        sql(relate),
        sql(r.source),
        sql(r.source_type ?? 'internet'),
        r.validated_count ?? 0,
        r.confidence ?? 'NULL',
        sql(r.notes),
      ].join(',')})`;
    }).join(',\n  ');
    console.log(`INSERT INTO internet (jd,name,event_label,type,country,tier,lat,lng,time_utc,lagna_sign,relate_id,source,source_type,validated_count,confidence,notes) VALUES\n  ${values};\n`);
  }
}

function sql(v) {
  if (v === null || v === undefined) return 'NULL';
  return `'${String(v).replace(/'/g, "''")}'`;
}
